import Navbar from "@components/Navbar"
import Head from "next/head"

export async function getServerSideProps({params}) {
  const res = await fetch(`${process.env.API_URL}/api/posts/detail/${params.id}`)
  const post = await res.json()
  return {
    props: { post }
  }
}

export default function SSR({post}) {
  return (
    <>
      <Head>
        <title>getServerSideProps | Next 13 Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 ">
          <h1 className="dark:text-white text-2xl font-semibold">getServerSideProps</h1>
          <h2 className="dark:text-white text-xl font-medium mt-2">Detail Post</h2>

          <div className="my-8 dark:text-white">
            <h3 className="dark:text-white text-xl font-medium mt-1">{post.title}</h3>
            <p className="dark:text-gray-300 text-neutral-600 mt-2">{post.body}</p>
          </div>

        </div>
      </main >
    </>
  )
}