import Head from 'next/head'
import Navbar from '@components/Navbar';
import Link from 'next/link';
import Code from '@components/Code';

const linkClassName = "text-sky-500 hover:text-sky-600 transition-all text-sm font-medium block mb-1"

export default function Home() {

  return (
    <>
      <Head>
        <title>Fonts | Next 13 Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 ">
          <h1 className="dark:text-white text-2xl font-semibold mb-2">Example Fonts Usage</h1>

          <div className="grid sm:grid-cols-2 md:grid-cols-4">
            <div>
              <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5">Plus Jakarta Sans</h2>
              <p className="dark:text-white pb-2">Regular 400</p>
              <p className="dark:text-white font-medium pb-2">Medium 500</p>
              <p className="dark:text-white font-semibold pb-2">SemiBold 600</p>
              <p className="dark:text-white font-bold pb-2">Bold 700</p>
              <p className="dark:text-white font-extrabold pb-2">Bold 800</p>
            </div>
            <div>
              <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-montserrat">Montserrat</h2>
              <p className="dark:text-white pb-2 font-montserrat">Regular 400</p>
              <p className="dark:text-white font-medium pb-2 font-montserrat">Medium 500</p>
              <p className="dark:text-white font-semibold pb-2 font-montserrat">SemiBold 600</p>
              <p className="dark:text-white font-bold pb-2 font-montserrat">Bold 700</p>
              <p className="dark:text-white font-extrabold pb-2 font-montserrat">Bold 800</p>
            </div>
            <div>
              <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-poppins">Poppins</h2>
              <p className="dark:text-white pb-2 font-poppins">Regular 400</p>
              <p className="dark:text-white font-medium pb-2 font-poppins">Medium 500</p>
              <p className="dark:text-white font-semibold pb-2 font-poppins">SemiBold 600</p>
              <p className="dark:text-white font-bold pb-2 font-poppins">Bold 700</p>
              <p className="dark:text-white font-extrabold pb-2 font-poppins">Bold 800</p>
            </div>
            <div>
              <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-inter">Inter</h2>
              <p className="dark:text-white pb-2 font-inter">Regular 400</p>
              <p className="dark:text-white font-medium pb-2 font-inter">Medium 500</p>
              <p className="dark:text-white font-semibold pb-2 font-inter">SemiBold 600</p>
              <p className="dark:text-white font-bold pb-2 font-inter">Bold 700</p>
              <p className="dark:text-white font-extrabold pb-2 font-inter">Bold 800</p>
            </div>
          </div>

          <Code name="pages/_document.js" className="mb-4" code={`import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}`} />

          <Code name="tailwind.config.js" className="mb-4" code={`const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        montserrat: ["Montserrat", ...defaultTheme.fontFamily.sans],
        poppins: ["Poppins", ...defaultTheme.fontFamily.sans],
        inter: ["Inter", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  variants: {},
  plugins: [
    require('@tailwindcss/forms')
    // require("tailwind-scrollbar"),
  ],
}`} />

          <Code name="styles/globals.css" className="mb-4" code={`@tailwind base;
@tailwind components;
@tailwind utilities;

html {
	scroll-behavior: smooth;
}

body {
	overflow-x: hidden;
	font-family: 'Plus Jakarta Sans', sans-serif;
}
`} />

          <Code name="pages/fonts" className="mb-4" code={`<h2 className="dark:text-white text-xl font-semibold pb-3 pt-5">Plus Jakarta Sans</h2>
<p className="dark:text-white pb-2">Regular 400</p>
<p className="dark:text-white font-medium pb-2">Medium 500</p>
<p className="dark:text-white font-semibold pb-2">SemiBold 600</p>
<p className="dark:text-white font-bold pb-2">Bold 700</p>
<p className="dark:text-white font-extrabold pb-2">Bold 800</p>

<h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-montserrat">Montserrat</h2>
<p className="dark:text-white pb-2 font-montserrat">Regular 400</p>
<p className="dark:text-white font-medium pb-2 font-montserrat">Medium 500</p>
<p className="dark:text-white font-semibold pb-2 font-montserrat">SemiBold 600</p>
<p className="dark:text-white font-bold pb-2 font-montserrat">Bold 700</p>
<p className="dark:text-white font-extrabold pb-2 font-montserrat">Bold 800</p>

<h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-poppins">Poppins</h2>
<p className="dark:text-white pb-2 font-poppins">Regular 400</p>
<p className="dark:text-white font-medium pb-2 font-poppins">Medium 500</p>
<p className="dark:text-white font-semibold pb-2 font-poppins">SemiBold 600</p>
<p className="dark:text-white font-bold pb-2 font-poppins">Bold 700</p>
<p className="dark:text-white font-extrabold pb-2 font-poppins">Bold 800</p>

<h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-inter">Inter</h2>
<p className="dark:text-white pb-2 font-inter">Regular 400</p>
<p className="dark:text-white font-medium pb-2 font-inter">Medium 500</p>
<p className="dark:text-white font-semibold pb-2 font-inter">SemiBold 600</p>
<p className="dark:text-white font-bold pb-2 font-inter">Bold 700</p>
<p className="dark:text-white font-extrabold pb-2 font-inter">Bold 800</p>`} />

        </div>
      </main >
    </>
  )
}
