import Head from 'next/head'
import Navbar from '@components/Navbar';
import Link from 'next/link';
import Code from '@components/Code';

const linkClassName = "text-sky-500 hover:text-sky-600 transition-all text-sm font-medium block mb-1"

export default function Home() {

  return (
    <>
      <Head>
        <title>next/link | Next 13 Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 ">
          <h1 className="dark:text-white text-2xl font-semibold mb-2">Example next/link next 13</h1>
          <p className="dark:text-white pb-2">{`next/link no longer requires manually adding <Link> as a child.`}</p>
          
          <Link href="/" className={linkClassName}>
            Home
          </Link>
          <Link href="/ssr" className={linkClassName}>
            SSR
          </Link>
          <Link href="/csr" className={linkClassName}>
            CSR
          </Link>
          <Link href="/image" className={linkClassName}>
            next/image
          </Link>
          <Link href="/link" className={linkClassName}>
            next/link
          </Link>
          <Link href="/font" className={linkClassName}>
            next/font
          </Link>

          <Code className="mb-4" code={`import Link from 'next/link';

const linkClassName = "text-sky-500 hover:text-sky-600 transition-all text-sm font-medium block mb-1"

<Link href="/" className={linkClassName}>
  Home
</Link>
<Link href="/ssr" className={linkClassName}>
  SSR
</Link>
<Link href="/csr" className={linkClassName}>
  CSR
</Link>
<Link href="/image" className={linkClassName}>
  next/image
</Link>
<Link href="/link" className={linkClassName}>
  next/link
</Link>
<Link href="/font" className={linkClassName}>
  next/font
</Link>`} />

        </div>
      </main >
    </>
  )
}
