import Head from 'next/head'
import Navbar from '@components/Navbar';
import Code from '@components/Code';

export default function Tailwind() {

  return (
    <>
      <Head>
        <title>next/fonts | Next 13 Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 ">
          <h1 className="dark:text-white text-2xl font-semibold mb-2">Example next/fonts Usage with Tailwind</h1>
          <a href='https://nextjs.org/docs/app/building-your-application/optimizing/fonts#with-tailwind-css' target='_blank' className="text-blue-500">ref</a>
          <div className="grid sm:grid-cols-2 md:grid-cols-4">
            <div>
              <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-inters">Inter</h2>
              <p className="dark:text-white pb-2 font-inters">Regular 400</p>
              <p className="dark:text-white font-medium pb-2 font-inters">Medium 500</p>
              <p className="dark:text-white font-semibold pb-2 font-inters">SemiBold 600</p>
              <p className="dark:text-white font-bold pb-2 font-inters">Bold 700</p>
              <p className="dark:text-white font-extrabold pb-2 font-inters">Bold 800</p>
            </div>
            <div>
              <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-robotomono">Roboto Mono</h2>
              <p className="dark:text-white pb-2 font-robotomono">Regular 400</p>
              <p className="dark:text-white font-medium pb-2 font-robotomono">Medium 500</p>
              <p className="dark:text-white font-semibold pb-2 font-robotomono">SemiBold 600</p>
              <p className="dark:text-white font-bold pb-2 font-robotomono">Bold 700</p>
              <p className="dark:text-white font-extrabold pb-2 font-robotomono">Bold 800</p>
            </div>
            <div>
              <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-playfair">Playfair</h2>
              <p className="dark:text-white pb-2 font-playfair">Regular 400</p>
              <p className="dark:text-white font-medium pb-2 font-playfair">Medium 500</p>
              <p className="dark:text-white font-semibold pb-2 font-playfair">SemiBold 600</p>
              <p className="dark:text-white font-bold pb-2 font-playfair">Bold 700</p>
              <p className="dark:text-white font-extrabold pb-2 font-playfair">Bold 800</p>
            </div>
            <div>
              <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-raleway">Raleway</h2>
              <p className="dark:text-white pb-2 font-raleway">Regular 400</p>
              <p className="dark:text-white font-medium pb-2 font-raleway">Medium 500</p>
              <p className="dark:text-white font-semibold pb-2 font-raleway">SemiBold 600</p>
              <p className="dark:text-white font-bold pb-2 font-raleway">Bold 700</p>
              <p className="dark:text-white font-extrabold pb-2 font-raleway">Bold 800</p>
            </div>
            <div>
              <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-roboto">Roboto</h2>
              <p className="dark:text-white pb-2 font-roboto">Regular 400</p>
              <p className="dark:text-white font-medium pb-2 font-roboto">Medium 500</p>
              <p className="dark:text-white font-semibold pb-2 font-roboto">SemiBold 600</p>
              <p className="dark:text-white font-bold pb-2 font-roboto">Bold 700</p>
              <p className="dark:text-white font-extrabold pb-2 font-roboto">Bold 800</p>
            </div>
          </div>

          <p className="dark:text-white mt-4">To use the font in all your pages, add it to _app.js file under /pages as shown below:</p>
          <Code name="pages/_app" className="mb-4" code={`import { Inter, Roboto_Mono, Playfair_Display, Raleway, Roboto } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})
const playfair = Playfair_Display({ subsets: ['latin'], variable: '--font-playfair' })
const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' })
const roboto = Roboto({ subsets: ['latin'], weight: '400', variable: '--font-roboto' })

function MyApp({ Component, pageProps }) {
  return (
    <GlobalProvider>
      <div className={"$ {inter.variable} $ {roboto_mono.variable} $ {playfair.variable} $ {raleway.variable} $ {roboto.variable}"}>
        <Component {...pageProps} />
      </div>
    </GlobalProvider>
  )
}`} />

          <Code name="tailwind.config.js" className="mb-4" code={`module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        inters: ['var(--font-inter)'],
        robotomono: ['var(--font-roboto-mono)'],
        playfair: ['var(--font-playfair)'],
        raleway: ['var(--font-raleway)'],
        roboto: ['var(--font-roboto)'],
      },
    },
  },
  variants: {},
  plugins: [
    require('@tailwindcss/forms')
  ],
}`} />

          <Code name="pages/tailwind" className="mb-4" code={`<div>
  <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-inters">Inter</h2>
  <p className="dark:text-white pb-2 font-inters">Regular 400</p>
  <p className="dark:text-white font-medium pb-2 font-inters">Medium 500</p>
  <p className="dark:text-white font-semibold pb-2 font-inters">SemiBold 600</p>
  <p className="dark:text-white font-bold pb-2 font-inters">Bold 700</p>
  <p className="dark:text-white font-extrabold pb-2 font-inters">Bold 800</p>
</div>
<div>
  <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-robotomono">Roboto Mono</h2>
  <p className="dark:text-white pb-2 font-robotomono">Regular 400</p>
  <p className="dark:text-white font-medium pb-2 font-robotomono">Medium 500</p>
  <p className="dark:text-white font-semibold pb-2 font-robotomono">SemiBold 600</p>
  <p className="dark:text-white font-bold pb-2 font-robotomono">Bold 700</p>
  <p className="dark:text-white font-extrabold pb-2 font-robotomono">Bold 800</p>
</div>
<div>
  <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-playfair">Playfair</h2>
  <p className="dark:text-white pb-2 font-playfair">Regular 400</p>
  <p className="dark:text-white font-medium pb-2 font-playfair">Medium 500</p>
  <p className="dark:text-white font-semibold pb-2 font-playfair">SemiBold 600</p>
  <p className="dark:text-white font-bold pb-2 font-playfair">Bold 700</p>
  <p className="dark:text-white font-extrabold pb-2 font-playfair">Bold 800</p>
</div>
<div>
  <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-raleway">Raleway</h2>
  <p className="dark:text-white pb-2 font-raleway">Regular 400</p>
  <p className="dark:text-white font-medium pb-2 font-raleway">Medium 500</p>
  <p className="dark:text-white font-semibold pb-2 font-raleway">SemiBold 600</p>
  <p className="dark:text-white font-bold pb-2 font-raleway">Bold 700</p>
  <p className="dark:text-white font-extrabold pb-2 font-raleway">Bold 800</p>
</div>
<div>
  <h2 className="dark:text-white text-xl font-semibold pb-3 pt-5 font-roboto">Roboto</h2>
  <p className="dark:text-white pb-2 font-roboto">Regular 400</p>
  <p className="dark:text-white font-medium pb-2 font-roboto">Medium 500</p>
  <p className="dark:text-white font-semibold pb-2 font-roboto">SemiBold 600</p>
  <p className="dark:text-white font-bold pb-2 font-roboto">Bold 700</p>
  <p className="dark:text-white font-extrabold pb-2 font-roboto">Bold 800</p>
</div>`} />

        </div>
      </main >
    </>
  )
}
